spring:
  #config:
    #import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:mysql://localhost:3308/ordersdb
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: orders
  profiles:
    active: default

