spring:
  application:
    name: "config-server"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/manikandan24vm/config-properties.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true
    group:
      liveness:
        include: livenessStateProbeIndicator, diskSpace, refreshScope
      readiness:
        include: readinessStateProbeIndicator

server:
  port: 8071
